
```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
library(DT)
knitr::opts_chunk$set(
	eval = T,
	echo = T,
	error = F,
	message = FALSE,
	warning = FALSE,
	cache = T,
	collapse = T,
	# fig.width = 5,
	fig.height = 4,
	unit = 'cm',
	fig.align = 'center'
)

rm(list = ls())  ## 魔幻操作，一键清空~
options(stringsAsFactors = F)

getOption('timeout')
options(timeout=10000) 
```

# GSEA 富集分析

## 加载数据
```{r}
# 加载包
library(org.Hs.eg.db)
library(clusterProfiler)
library(ggstatsplot)
library(ggplot2)

load(file = "Rdata/DEG_edgeR_reg.Rdata")
colnames(total)

# 输出文件夹
OUT_FOLDER <- "Anno_enrichment/GSEA"
dir.create(OUT_FOLDER, showWarnings = FALSE)

# 数据预处理
nrDEG <-  total[, c("SYMBOL","log2FoldChange", "FDR")]
colnames(nrDEG) <- c("SYMBOL", 'log2FC', 'FDR')
gene <- bitr(nrDEG$SYMBOL, 
             fromType = "SYMBOL",
             toType =  "ENTREZID",
             OrgDb = org.Hs.eg.db)
head(gene)
head(nrDEG)
nrDEG <- nrDEG[nrDEG$SYMBOL %in% gene$SYMBOL,]
nrDEG$ENTREZID <- gene$ENTREZID[match(nrDEG$SYMBOL, gene$SYMBOL)]

geneList <- nrDEG$log2FC
names(geneList) <- nrDEG$ENTREZID
geneList <- sort(geneList, decreasing = T)
head(geneList)
```


## GSEA 分析
```{r}
str(geneList)
kk_gse <- gseKEGG(geneList     = geneList,
                  organism     = 'hsa',#按需替换
                  minGSSize    = 10,
                  pvalueCutoff = 0.99,
                  verbose      = FALSE)
kk <- DOSE::setReadable(kk_gse, OrgDb='org.Hs.eg.db', # 将基因ID换为SYNBOL
                     keyType='ENTREZID')#按需替换
kk@result$Description <- gsub(' - Mus musculus \\(house mouse\\)',
                           '', kk@result$Description )
head(kk@result$Description)
tmp=kk@result 
```

```{r}
#～～～取前6个上调通路和6个下调通路～～～
up_k <- kk[head(order(kk$enrichmentScore,decreasing = T)),];up_k$group=1
down_k <- kk[tail(order(kk$enrichmentScore,decreasing = T)),];down_k$group=-1

dat <- rbind(up_k, down_k)

dat$`-log10Pvalue` <- -log10(dat$pvalue)*dat$group
dat <- dat[order(dat$`-log10Pvalue`, decreasing = F),]
ggplot(dat, aes(x=reorder(Description, order(`-log10Pvalue`, decreasing = F)), 
                      y=`-log10Pvalue`, fill=group)) + 
  geom_bar(stat="identity") + 
  scale_fill_gradient(low="#34bfb5",high="#ff6633",guide = FALSE) + 
  labs(x="Pathway names", y="-log10Pvalue") +
  coord_flip() + 
  theme_ggstatsplot()+
  theme(plot.title = element_text(size = 10, hjust = 0.5),  
        axis.text = element_text(size = 8),
        panel.grid = element_blank()
        )+
  ggtitle("Pathway Enrichment")
```

```{r}
up_k <- kk[head(order(kk$enrichmentScore,decreasing = T)),];up_k$group=1
down_k <- kk[tail(order(kk$enrichmentScore,decreasing = T)),];down_k$group=-1

p_up <- enrichplot::gseaplot2(kk, geneSetID = head(rownames(up_k)));p_up
p_down <- enrichplot::gseaplot2(kk, geneSetID = head(rownames(down_k)));p_down
```


## 保存结果
保存结果
```{r}
write.csv(kk@result, file = file.path(paste0(OUT_FOLDER, '/gsea_kegg.csv')), row.names = F)
```
保存变量
```{r}
save(kk, file = 'Rdata/gsea_kk.Rdata')
```
